---
language: objective-c

osx_image: xcode11.1

cache:
  directories:
    - Carthage

env:
  global:
    - WORKSPACE=GEOSwift.xcworkspace
  matrix:
    - PLATFORM=iOS
      SCHEME=GEOSwift-iOS
      SDK=iphonesimulator13.1
      DESTINATION="platform=iOS Simulator,OS=13.1,name=iPhone 11"
      RUN_CODECOV=true
    - PLATFORM=tvOS
      SCHEME=GEOSwift-tvOS
      SDK=appletvsimulator13.0
      DESTINATION="platform=tvOS Simulator,OS=13.0,name=Apple TV"
      RUN_CODECOV=false
    - PLATFORM=macOS
      SCHEME=GEOSwift-macOS
      SDK=macosx10.15
      DESTINATION="platform=OS X"
      RUN_CODECOV=false

before_install:
  - brew install carthage swiftlint
  - gem install xcpretty
  - travis_wait 30 carthage update
      --cache-builds
      --platform "$PLATFORM"
      --no-use-binaries

script:
  - set -o pipefail
  - xcodebuild
      -workspace "$WORKSPACE"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION"
      -configuration Debug
      ONLY_ACTIVE_ARCH=YES
      clean test | xcpretty -c;

after_success:
  - if [ "${RUN_CODECOV}" = "true" ]; then
      bash <(curl -s https://codecov.io/bash) -J '^GEOSwift$';
    fi
