language: objective-c

before_install:
  - gem install xcpretty
  - gem install cocoapods -v '1.5.3'
  - pod repo update
  - pod install --verbose
  - brew install swiftlint

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^GEOSwift$'

osx_image: xcode9.4

cache: cocoapods

env:
  global:
    - WORKSPACE=GEOSwift.xcworkspace
    - SCHEME=GEOSwift
    - SDK=iphonesimulator11.4
  matrix:
    - DESTINATION="OS=11.4,name=iPhone X"

script:
  - set -o pipefail
  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;
