language: objective-c

before_install:
  - gem install xcpretty
  - gem install cocoapods -v '1.5.0'
  - pod repo update
  - pod install --verbose

osx_image: xcode9.2

cache: cocoapods

env:
  global:
    - WORKSPACE=GEOSwift.xcworkspace
    - SCHEME=GEOSwift
    - SDK=iphonesimulator11.2
  matrix:
    - DESTINATION="OS=11.2,name=iPhone 8"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Release
    ONLY_ACTIVE_ARCH=YES
    ENABLE_TESTABILITY=YES
    clean test | xcpretty -c;
